#!/bin/bash

# Variables pour la génération des certificats
country="FR"
state="BFC"
city="Montbeliard"
organization="IUT"
common_name_CA=""
common_name_mosquitto="192.168.1.50"

# Vérifier si les certificats existent déjà
if [ ! -f "/etc/mosquitto/certs/ca.crt" ]; then
  # Génération du certificat auto-signé CA s'il n'existe pas
  openssl genrsa -des3 -out ca.key 2048
  openssl req -new -x509 -days 1826 -key ca.key -out ca.crt\
         -subj "/C=$country/ST=$state/L=$city/O=$organization/CN=$common_name_CA"
fi

if [ ! -f "/etc/mosquitto/certs/$1.crt" ] || [ ! -f "/etc/mosquitto/certs/$1.key" ]; then
   # Génération du certificat pour le serveur MQTT s'ils n'existent pas
   openssl genrsa -out $1.key 2048
   openssl req -new -out $1.csr -key $1.key \
      -subj "/C=$country/ST=$state/L=$city/O=$organization/CN=$common_name_mosquitto"
   openssl x509 -req -in $1.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out $1.crt -days 360
fi


chmod 644 /etc/mosquitto/certs/*
