#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Utilisation: $0 <topic> <message>"
    echo "Exemple: $0 mytopic 'Hello, world!'"
    exit 1
fi

topic=$1
message=$2
dir=/etc/mosquitto/certs

mosquitto_pub -h 192.168.1.5 -p 8883 -u Solgaleo -P Lunala -t "$topic" -m "$message" --cafile $dir/ca.crt --insecure -d
