#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Utilisation: $0 <topic> <message>"
    echo "Exemple: $0 mytopic 'Hello, world!'"
    exit 1
fi

topic=$1
message=$2
dir=/etc/mosquitto/certs

mosquitto_pub -h 192.168.50.25 -p 8883 -t "$topic" -m "$message" --cafile ca.crt --cert $3.crt --key $3.key -d
